# Generated by Django 4.1.7 on 2023-02-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountJokeModel',
            fields=[
                ('user_chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('fat_count', models.IntegerField()),
                ('dumb_count', models.IntegerField()),
                ('stupid_count', models.IntegerField()),
            ],
        ),
    ]
