# Generated by Django 4.1.7 on 2023-02-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countjokemodel',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='countjokemodel',
            name='user_id',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
